version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - nginx-gen
      - nginx-letsencrypt
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - ./volumes/proxy/templates:/etc/docker-gen/templates
      - ./volumes/proxy/vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:rw
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: unless-stopped
  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    depends_on:
      - nginx-letsencrypt
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - ./volumes/proxy/templates:/etc/docker-gen/templates
      - ./volumes/proxy/vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:rw
    environment:
      - ENABLE_IPV6=true
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: unless-stopped
  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - ./volumes/proxy/vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:rw
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    restart: unless-stopped
  shinyproxy:
    container_name: shinyproxy
    image: martinmontane/shinyproxy_utf8
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy/:/opt/shinyproxy/app_yml:rw
    environment:
      - VIRTUAL_HOST=DOMINIO
      - VIRTUAL_NETWORK=shinyproxy-net
      - LETSENCRYPT_HOST=DOMINIOAENCRIPTAR
      - LETSENCRYPT_EMAIL=MAILDEREPORTE
    restart: unless-stopped
volumes:
  nginx-conf:
  nginx-html: 
  nginx-vhost:
  nginx-certs:
networks:
  default:
    external:
      name: shinyproxy-net
