proxy:
  template-path: ./templates/2col
  title: Open Analytics Shiny Proxy
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 120000
  container-wait-time: 120000
  port: 8080
  authentication: none
  hide-navbar: true
  container-backend: docker
  docker:
      internal-networking: true
  specs:
  - id: testapp
    display-name: shinyapptest
    description: Primera shiny app en este servidor local
    container-cmd: ["R", "-e", "shiny::runApp('/root/firstapp')"]
    container-network: redshinyproxy
    container-image: testappimage
logging:
  file:
    shinyproxy.log
