proxy:
  template-path: ./templates/2col
  title: Open Analytics Shiny Proxy
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 120000
  container-wait-time: 120000
  port: 8080
  authentication: none
  hide-navbar: true
  container-backend: docker
  docker:
      internal-networking: true
  specs:
  - id: mapavicentelopez
    display-name: Mapa Interactivo de OSC
    description: Mapa interactivo de las OSC de Vicente Lopez. En desarrollo
    container-cmd: ["R", "-e", "shiny::runApp('/root/mapavicentelopez')"]
    container-network: shinyproxy-net
    container-image: mapavicentelopez

logging:
  file:
    shinyproxy.log
